language: objective-c
os: osx
xcode_project: src/XCode/LocalNotificationLib/LocalNotificationLib.xcodeproj
xcode_scheme: LocalNotificationTests
script: script/build
matrix:
  include:
      - osx_image: xcode9
        env: XCODE_DESTINATION="platform=iOS Simulator,OS=11,name=iPhone 5s"
      - osx_image: xcode8.3
        env: XCODE_DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 5"
      - osx_image: xcode8.2
        env: XCODE_DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 4s"
      - osx_image: xcode8.2
        env: XCODE_DESTINATION="platform=iOS Simulator,OS=8.4,name=iPhone 4s"
      - osx_image: xcode8.2
        env: XCODE_DESTINATION="platform=iOS Simulator,OS=8.1,name=iPhone 4s"
