xcode_project: src/XCode/LocalNotificationLib/LocalNotificationLib.xcodeproj
xcode_scheme: LocalNotificationTests

script: script/build

matrix:
  include:
      - language: objective-c
        os: osx
        osx_image: xcode9
        env: XCODE_DESTINATION="platform=iOS Simulator,OS=11.0,name=iPhone 5s"
      - language: objective-c
        os: osx
        osx_image: xcode8.3
        env: XCODE_DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 5"
      - language: objective-c
        os: osx
        osx_image: xcode8.2
        env: XCODE_DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 4s"
      - language: objective-c
        os: osx
        osx_image: xcode8.2
        env: XCODE_DESTINATION="platform=iOS Simulator,OS=8.4,name=iPhone 4s"
      - language: objective-c
        os: osx
        osx_image: xcode8.2
        env: XCODE_DESTINATION="platform=iOS Simulator,OS=8.1,name=iPhone 4s"
      - language: android
        env: LANG=Android
        android:
          components:
            - tools
            - platform-tools
            - tools
            - android-26
            - build-tools-27.0.3
        licenses:
          - 'android-sdk-license-.+'

