#!/bin/zsh

source ./bin/config/config.sh

SDK_PATH="$HOME/Developer/AIR_SDK"
ASDOC_PATH="$SDK_PATH/bin/asdoc"

rm -rf ./doc

"$ASDOC_PATH" \
	-define+=CONFIG::device,false \
	-define+=CONFIG::iphone,false \
	-define+=CONFIG::android,false \
  -library-path+=$SDK_PATH/frameworks/libs/air/airglobal.swc \
  -source-path ./src/AS/src \
  -doc-sources ./src/AS/src \
  -output doc
