#!/bin/zsh

# name of APP file
APP_NAME=sample

# Certificate password
CERT_FILE=test_ios.p12
CERT_PASS=1234
PROVISIONING_PROFILE=test.mobileprovision
IPHONE_SDK="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk"

RES_PATH="$EXT_PATH/../res"

echo "***** IOS APP ******"
echo "***** compiling SWF file *****"

"$AMXML" -swf-version $SWF_VERSION \
  -define+=CONFIG::device,true \
  -define+=CONFIG::iphone,true \
  -define+=CONFIG::android,false \
  -external-library-path+=$EXT_PATH/LocalNotificationLib.ane \
  -output $APP_NAME.swf \
  -- Sample.as

