#!/bin/zsh

set -e
source ../../bin/config/config.sh
BUILD_ANE_PATH="$EXT_PATH/../build-ane-android"

source prepare_android

echo "***** packaging SWF file into APK *****"

# options: apk, apk‑captive‑runtime, apk-debug, apk-emulator, apk-profile
"$ADT" -package \
  -target apk-captive-runtime \
  -storetype pkcs12 -keystore $CERT_FILE \
  -storepass $CERT_PASS \
  -keypass $CERT_PASS \
  $APP_NAME.apk \
  ${APP_NAME}-app.xml \
  $APP_NAME.swf \
  -extdir $EXT_PATH

# For these steps the device must be running
# Set -device if more than one device is running.
# To list devices: adt -devices -platform iOS|android

echo "**** Install app in Android device ******"

"$ADT" -installApp \
  -platform android \
  -package $APP_NAME.apk
