#!/bin/zsh

set -e
source ../../bin/config/config.sh

export AIR_IOS_SIMULATOR_DEVICE="iPhone 5"

source prepare_ios

echo "***** packaging SWF file into IPA *****"

# other targets: ipa-test, ipa-debug, ipa-debug-interpreter, ipa-app-store, ipa-app-store, ipa-ad-hoc
"$ADT" -package \
  -target ipa-test-interpreter-simulator \
  -storetype pkcs12 -keystore $CERT_FILE \
  -storepass $CERT_PASS \
  $APP_NAME.ipa \
  ${APP_NAME}-app.xml \
  $APP_NAME.swf \
  fx05.caf \
  -extdir $EXT_PATH

echo "**** Installing IPA in iOS simulator ******"


"$ADT" -installApp \
  -platform ios \
  -device ios-simulator \
  -package $APP_NAME.ipa

echo "**** Launching iOS simulator ******"

"$ADT" -launchApp \
  -platform ios \
  -device ios-simulator \
  -appid com.juankpro.Sample
