#!/bin/zsh

set -e
source ../../bin/config/config.sh
BUILD_ANE_PATH="$EXT_PATH/../build-ane-android-emulator"

source prepare_android

echo "***** packaging SWF file into APK *****"

# options: apk, apk‑captive‑runtime, apk-debug, apk-emulator, apk-profile
"$ADT" -package \
  -target apk-emulator \
  -arch x86 \
  -storetype pkcs12 -keystore $CERT_FILE \
  -storepass $CERT_PASS \
  -keypass $CERT_PASS \
  $APP_NAME.apk \
  ${APP_NAME}-app.xml \
  $APP_NAME.swf \
  -extdir $EXT_PATH

# To install successfully emulator must be running.
# Create and configure an emulator then run it.
# Set -device if more than one device is running.
# To list devices: adt -devices -platform iOS|android

echo "**** Install app in Android emulator ******"

"$ADT" -installApp \
  -platform android \
  -package $APP_NAME.apk
