#!/bin/zsh

set -e

SDK="$HOME/Developer/AIR_SDK"
AMXML="$SDK/bin/amxmlc"
ADT="$SDK/bin/adt"
ANDROID_SDK="$HOME/Library/Android/sdk"
EXT_DIR="../../bin/ext"

# name of APP file
APP_NAME=sample

# Certificate password
CERT_FILE=test_android.p12
CERT_PASS=1234

echo "***** COPYING ANE RESOURCES"
if [ -d "$EXT_DIR/res" ]; then
  rm -rf $EXT_DIR
fi
cp -R res $EXT_DIR/..

$EXT_DIR/../build-ane-android

echo "***** ANDROID APP ******"
echo "***** compiling SWF file *****"
"$AMXML" -swf-version 26 \
  -define+=CONFIG::device,true \
  -define+=CONFIG::iphone,false \
  -define+=CONFIG::android,true \
  -external-library-path+=./../../bin/ext/LocalNotificationLib.ane \
  -output ./$APP_NAME.swf \
  -- ./Sample.as

echo "***** packaging SWF file into APK *****"

# options: apk, apk‑captive‑runtime, apk-debug, apk-emulator, apk-profile
"$ADT" -package \
  -target apk-captive-runtime \
  -storetype pkcs12 -keystore $CERT_FILE \
  -storepass $CERT_PASS \
  -keypass $CERT_PASS \
  $APP_NAME.apk \
  ${APP_NAME}-app.xml \
  $APP_NAME.swf \
  -extdir $EXT_DIR

# For these steps the device must be running

# NOTE: Uncomment this if compiling non-captive APK
#echo "**** Install AIR SDK in Android emulator *****"
#"$ADT" -installRuntime \
#  -platform android \
#  -platformsdk "$ANDROID_SDK"

echo "**** Install app in Android device ******"

"$ADT" -installApp \
  -platform android \
  -package $APP_NAME.apk
