#!/bin/zsh

set -e

SDK="${HOME}/Developer/AIR_SDK"
AMXML="${SDK}/bin/amxmlc"
ADT="${SDK}/bin/adt"

# name of ipa file
APP_NAME=sample

# Certificate
CERT_FILE=test.p12
CERT_PASS=1234
PROVISIONING_PROFILE=test.mobileprovision

echo "***** IOS SIMULATOR APP ******"
echo "***** compiling SWF file *****"
"$AMXML" -swf-version 26 \
  -debug=true \
  -define+=CONFIG::device,true \
  -define+=CONFIG::iphone,true \
  -define+=CONFIG::android,false \
  -external-library-path+=./../../bin/ext/LocalNotificationLib.ane \
  -output ./$APP_NAME.swf \
  -- ./Sample.as

echo "***** packaging SWF file into IPA *****"

# other targets: ipa-test, ipa-debug, ipa-debug-interpreter, ipa-app-store, ipa-app-store, ipa-ad-hoc
"$ADT" -package \
  -target ipa-test-interpreter \
  -storetype pkcs12 -keystore $CERT_FILE \
  -storepass $CERT_PASS \
  -provisioning-profile $PROVISIONING_PROFILE\
  $APP_NAME.ipa \
  ${APP_NAME}-app.xml \
  $APP_NAME.swf \
  fx05.caf \
  -extdir ./../../bin/ext

echo "**** Installing IPA in iOS simulator ******"

"$ADT" -installApp \
  -platform ios \
  -device 1 \
  -package APP_NAME.ipa

echo "**** Lanching iOS simulator ******"

"$ADT" -launchApp \
  -platform ios \
  -device 1 \
  -appid com.juankpro.Sample
