#!/bin/zsh

set -e
source ../../bin/config/config.sh

DEVICE_ID=4

source prepare_ios

echo "***** packaging SWF file into IPA *****"

# other targets: ipa-test, ipa-debug, ipa-debug-interpreter, ipa-app-store, ipa-app-store, ipa-ad-hoc
"$ADT" -package \
  -target ipa-test-interpreter \
  -storetype pkcs12 -keystore $CERT_FILE \
  -storepass $CERT_PASS \
  -provisioning-profile $PROVISIONING_PROFILE\
  $APP_NAME.ipa \
  ${APP_NAME}-app.xml \
  $APP_NAME.swf \
  fx05.caf \
  -extdir $EXT_PATH

echo "**** Installing IPA in iOS simulator ******"

"$ADT" -installApp \
  -platform ios \
  -device $DEVICE_ID \
  -package $APP_NAME.ipa

echo "**** Lanching iOS simulator ******"

"$ADT" -launchApp \
  -platform ios \
  -device $DEVICE_ID \
  -appid com.juankpro.Sample
