#!/bin/bash

set -ev

if [ "$LANG" = "Android" ]
then
  cd $TRAVIS_BUILD_DIR/src/AndroidStudio/LocalNotificationLib
  ./gradlew test
else
  cd $TRAVIS_BUILD_DIR/src/XCode/LocalNotificationLib

  xcodebuild test \
    -project LocalNotificationLib.xcodeproj \
    -scheme LocalNotificationTests \
    -destination "$XCODE_DESTINATION"
fi
